version: '3'

services:
  docker-nuttx-bash:
    image:  docker-nuttx
    build:
      context: .
    stdin_open: true
    tty: true
    environment:
      - USER_ID
      - GROUP_ID
    volumes:
      - ${PWD}/nuttx:/nuttx
      - ${PWD}/apps:/apps
    working_dir: "/nuttx"

  docker-nuttx-configure:
    image:  docker-nuttx
    stdin_open: true
    tty: true
    environment:
      - USER_ID
      - GROUP_ID
      - BOARD_NAME
      - CONFIG_NAME
    volumes:
      - ${PWD}/nuttx:/nuttx
      - ${PWD}/apps:/apps
    working_dir: "/nuttx"
    command: ["./tools/configure.sh ${BOARD_NAME}:${CONFIG_NAME}"]

  docker-nuttx-build:
    image:  docker-nuttx
    stdin_open: true
    tty: true
    environment:
      - USER_ID
      - GROUP_ID
    volumes:
      - ${PWD}/nuttx:/nuttx
      - ${PWD}/apps:/apps
    working_dir: "/nuttx"
    command: ["make"]